### ISSUE TITLE
Halo center

### ISSUE THREAD

**Issue by henedler** [JortBox/Halo-FDCA#8]
Hi Jort, 
I revisited you code and the fitting again, and I found what seems to be an issue in the halo center calculation.

My fit looks like this in the output plot, seems very reasonable to me:
![grafik](https://user-images.githubusercontent.com/56255383/109934014-523f8800-7ccc-11eb-810d-563d72509799.png)

Now, the log containing the fit result gives the following center (these are the results, not the initial guess values):
```
x0    157.883355
y0     35.070974
r1    154.126604
One sigma parameter uncertainties (lower, upper):                                     
[5.61247731e-04 4.99528646e-04 2.24091591e+00] 
[5.35861851e-04 5.04987999e-04 2.30566808e+00] 
```

It looks to me like the center of the plot above and the center printed in the logs do not agree. In addition, it seems like the coordinate system in the plot is shifted compared to the input image (around 3.6 arcmin). 

For comparison, this is what it looks like if I place a region on the input image with the properties from the logs:
![grafik](https://user-images.githubusercontent.com/56255383/109935356-caf31400-7ccd-11eb-9090-d9e70fe836d0.png)

The issue seems to be only the absolute coordinate system, the results itself, flux, fit etc. look good.
(I am using tag v1.3.)

**Comment by JortBox** [comment]
Thank you for your comment. This is an unfortunate error since I believe it is solved by simply replacing w.celestial.wcs_pix2world(cent_pix,0)    -->   w.celestial.wcs_pix2world(cent_pix,1) everywhere. I did just that so I hope the location calculations are working now.

**Comment by botteon** [comment]
Hi, Luca Bruno and I also noticed this issue in the past. Can Henrik confirm that the issue is solve with commit https://github.com/JortBox/Halo-FDCA/commit/01bef3ccdcda8faa50c957d4263333ad3253e9da?

I did a test on a cluster that showed this problem but the commit doesn't seem to solve the issue.

![Screenshot from 2021-03-10 16-35-00](https://user-images.githubusercontent.com/23218111/110658314-dfe61080-81c1-11eb-8fe2-c42aa2c97510.png)

the centers of the two runs (before and after the commit) are very similar, and are out of the halo:

![Screenshot from 2021-03-10 16-35-13](https://user-images.githubusercontent.com/23218111/110658321-e1afd400-81c1-11eb-98a3-d474541e4f77.png)

**Comment by henedler** [comment]
@JortBox, thanks for looking into this!
Hi Andrea, I did not yet test the fix, will do that now. But if I understood the meaning of the 'origin' argument in the WCS correctly, then changing this from 1 to 0 will only offset everything by a single pixel, right? So I am not sure if this can solve the problem.

**Comment by henedler** [comment]
![image](https://user-images.githubusercontent.com/56255383/110829727-bd72f680-8298-11eb-8fea-b84d01c382d0.png)

This is now with the 1.4 release, the issue is still present.

**Comment by ErikOsinga** [comment]
I also found this issue when trying the latest version of the code. I'm not sure what is causing it, because when I input a test image with an easy-to-fit radio halo, the output coordinates seem correct. However, when I input my actual target there seems to be a large offset as well in the coordinates.

@henedler or @JortBox did you ever figure out what is causing this? 

I'm not sure whether it is only a visual bug (i.e. the center in the chain is correct) or because of a wrong conversion to WCS somewhere, but I suspect it at least has to do with these lines that plot the output (in plotting_fits.py)


```
    im1 = axes[0].imshow(masked_data,cmap='inferno', origin='lower',
                        extent=(ra.max(),ra.min(),dec.min(),dec.max()), norm = NORMres)

```
I don't think this extent=ra.max() is doing what is expected

**Comment by henedler** [comment]
Hi @ErikOsinga, I did not investigate the bug further. To me it looked like the coordinates in the plot are correct, but the ones that are printed in the logs are offset somehow.

**Comment by MarcoBalboni** [comment]
Hi all, I am facing the same issue.

I tried to dig a bit into the code. What I, may, have found is that the wrong coordinates are written down only when it increases the FoV with some padding because the halo is too large. In particular what returns wrong coordinate number is this part here in the markov_chain_monter_carlo.py module:

`params[1] = (params[1]-self.centre_pix[0])*self.halo.pix_size.value+self.centre_wcs[0].value` %RA
`params[2] = (params[2]-self.centre_pix[1])*self.halo.pix_size.value+self.centre_wcs[1].value` %DEC

I tried also to investigate how variable `self.centre_wcs` is defined. The conversion from pixel to WCS when defining it it's not straight forward to me. I understood how it is defined through `halo.ra`, but if I compare the conversion pixel-WCS made by the scripts with the one made on ds9 I found some differences.

I also inspected how the padding is made and seems good to me (same outcome are obtained when using padding images and FoV reduced ones).

My guess is that somewhere somehow the variable `halo.ra` (and `halo.dec`) is modified when padding and then wrong results are produced.

A workaround that may works is to perform a complete analysis with HFDCA on image with "small FoV" and then perform a second run with fewer steps (?) on a wider image so the code does not perform padding and use the latter result to recover the correct halo center.
Pay attention that if one masks "too much" then the FoV is reduced and then it performs padding.

**Comment by ErikOsinga** [comment]
Just FYI, instead of figuring out what the problem was, I made a simpler version of the code, from forking this repository, which I don't think has this bug (but then of course it has a lot fewer features), but you could try running that as well: 

https://github.com/ErikOsinga/Halo-FDCA_eo/

**Comment by botteon** [comment]
Every now and then I bump again into this issue, I read this thread, dig into the code, but do not find a solution...

Today I also found that DEC coordinates are reported wrong in the plots/log for clusters in the southern hemisphere (for example a target at DEC -80deg will have in the y-axis of the plot DEC values of +280 deg...), although this is probably another, unrelated, bug
